Testing
YunoHost-Apps/pluxml_ynh pull request #55
Opened 2021-06-12 18:29 UTC by ericgaspar

- Upgrade to v5.8.7

2021-06-12 18:32 UTC, ericgaspar commented
!testme

2021-06-15 18:07 UTC, yalh76 requested changes

2021-06-15 18:07 UTC, yalh76 commented on scripts/install
> +chown -R $app $final_path
Not sure i's needed or have to change L77

2021-06-16 13:01 UTC, ericgaspar commented
!testme

2021-06-16 19:30 UTC, yalh76 approved these changes
LGTM

2021-06-16 21:53 UTC, merged